# Generated by Django 4.2.6 on 2023-10-18 08:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImgGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(default='', max_length=50, verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='Имя')),
                ('mail', models.CharField(default='', max_length=50, verbose_name='Почта')),
                ('password', models.CharField(default='', max_length=50, verbose_name='Пароль')),
                ('birth_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата рождения')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='WordGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_question', models.CharField(default='', max_length=250, verbose_name='Наводящий вопрос')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='WordTranslate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default='', max_length=50, verbose_name='Имя')),
                ('translate', models.CharField(default='', max_length=50, verbose_name='Почта')),
                ('img', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.imggame')),
                ('lead_question', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.wordgame')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.users')),
            ],
            options={
                'verbose_name': 'Слово с переводом',
                'verbose_name_plural': 'Слова с переводом',
            },
        ),
    ]
