# Generated by Django 4.2.6 on 2023-10-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='password',
            new_name='password1',
        ),
        migrations.AddField(
            model_name='users',
            name='password2',
            field=models.CharField(default='', max_length=50, verbose_name='Пароль'),
        ),
    ]
